agents:
  hypothesis_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 1.0
  process_agent:
    provider: google
    model_config:
      model: gemini-2.5-pro
      temperature: 1.0
  visualization_agent:
    provider: openai
    model_config:
      model: gpt-5-nano
      temperature: 1.0
  code_agent:
    provider: anthropic
    model_config:
      model: claude-haiku-4-5
      temperature: 1.0
  search_agent:
    provider: google
    model_config:
      model: gemini-2.5-flash
      temperature: 1.0
  report_agent:
    provider: openai
    model_config:
      model: gpt-5-nano
      temperature: 1.0
  quality_review_agent:
    provider: openai
    model_config:
      model: gpt-5-mini
      temperature: 1.0
  note_agent:
    provider: google
    model_config:
      model: gemini-2.5-pro
      temperature: 1.0
  refiner_agent:
    provider: openai
    model_config:
      model: gpt-5-nano
      temperature: 1.0
